### ISSUE TITLE
Failed compiling cview

### ISSUE THREAD

**Issue by MinS1** [nloyfer/wgbs_tools#65]
Compiling stdin2beta...
SUCCESS
Compiling mask_pat...
SUCCESS
Compiling pat_sampler...
SUCCESS
Compiling patter...
SUCCESS
Compiling bp_patter...
SUCCESS
Compiling snp_patter...
SUCCESS
Compiling match_maker...
SUCCESS
Compiling segmentor...
SUCCESS
Compiling cview...
FAIL
Failed compilation.
Command: g++ -std=c++11 -c -o src/cview/cview.o src/cview/cview.cpp && g++ -std=c++11 -c -o src/pipeline_wgbs/patter_utils.o src/pipeline_wgbs/patter_utils.cpp && g++ -std=c++11 -o src/cview/cview src/cview/cview.o src/pipeline_wgbs/patter_utils.o
return code: 1
stderr:

stdout:
src/cview/cview.cpp: In member function ‘void Cview::parse()’:
src/cview/cview.cpp:178:78: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
         if (verbose) fprintf(stderr, "finished %s reads\n", addCommas(line_i));
                                                                              ^

Failed compiling cview
Compiling homog...
SUCCESS
Compiling add_cpg_counts...
SUCCESS
Compiling add_loci...
SUCCESS

**Comment by MinS1** [comment]
The problem has been solved.
But init_genome doesn't seem to work

**Comment by AzlanNI** [comment]
Hey MinS1, 
Would u mind telling how u solved this? I am currently having the same problem with cview failed

**Comment by AndreiWCansor** [comment]
@MinS1 
Same - having issues compiling cview.. please share how you get around with it please!

**Comment by AzlanNI** [comment]
@AndreiWCansor i change a little line in src/cview/cview.cpp 
line 178 
from 
if (verbose) fprintf(stderr, "finished %s reads\n", addCommas(line_i));
to
if (verbose) fprintf(stderr, "finished %s reads\n", addCommas(line_i).c_str());
After that all succeded but i still cant call wgbstools but maybe it helps u!

**Comment by AndreiWCansor** [comment]
@AzlanNI 
Great it's sorted thank you!!!

**Comment by AzlanNI** [comment]
@AndreiWCansor 
It is C++ compiled so i was working on Mac i had to use ./wgbstools in the directory $HOME/wbgs_tools 
then i added it to my Home $PATH and could use wgbstools from everywhere :) 
I hope that helps u out!
